# Generated by Django 3.2.8 on 2021-10-28 22:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 22, 1, 24, 840417, tzinfo=utc)),
        ),
    ]
