# Generated by Django 3.2.8 on 2021-10-29 02:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 2, 53, 7, 686541, tzinfo=utc)),
        ),
    ]
