# Generated by Django 3.2.8 on 2021-10-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211024_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('MS', 'Miscellaneous'), ('EL', 'Electronics'), ('CL', 'Clothing'), ('FD', 'Food'), ('HO', 'Home'), ('TO', 'Toys')], default='MS', max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
